name: Build the Docker Image

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: false
          build-args: |
            BROWSER_LICENSE_KEY=${{ secrets.BROWSER_LICENSE_KEY }},
            BROWSER_ACCOUNT_ID=${{ secrets.BROWSER_ACCOUNT_ID }},
            BROWSER_TRUST_KEY=${{ secrets.BROWSER_TRUST_KEY }},
            BROWSER_AGENT_ID=${{ secrets.BROWSER_AGENT_ID }},
            BROWSER_APPLICATION_ID=${{ secrets.BROWSER_APPLICATION_ID }}
